export const employeeData: any[] = [
    {
      id: 1,
      imageSrc: 'assets/img/avatars/1.jpg',
      name: 'Guerrero Morales',
      phone: '+21 (988) 504-2559',
      designation: 'Software developer',
      email: 'guerrero.morales@supportal.com',
      employeeStartDate: new Date('2022-03-15'),
      publicHolidayGroup: 'general',
      onBoardingMentor: 'Alice Johnson',
      directManager: 'John Smith',
      location: 'dhaka',
      team: 'angular',
      employeeStatus: 'full-time'
    },
    {
      id: 2,
      imageSrc: 'assets/img/avatars/2.jpg',
      name: 'Robin Blackburn',
      phone: '+5 (911) 423-2538',
      designation: 'Software developer',
      email: 'robin.blackburn@polarax.biz',
      employeeStartDate: new Date('2021-11-12'),
      publicHolidayGroup: 'uk',
      onBoardingMentor: 'David Brown',
      directManager: 'Jane Doe',
      location: 'london',
      team: 'devops',
      employeeStatus: 'full-time'
    },
    {
      id: 3,
      imageSrc: 'assets/img/avatars/3.jpg',
      name: 'Simone Gallegos',
      phone: '+2 (948) 573-3528',
      designation: 'Software developer',
      email: 'simone.gallegos@applidec.org',
      employeeStartDate: new Date('2020-08-30'),
      publicHolidayGroup: 'us',
      onBoardingMentor: 'Robert Wilson',
      directManager: 'Emma White',
      location: 'new-york',
      team: 'management',
      employeeStatus: 'full-time'
    },
    {
      id: 4,
      imageSrc: 'assets/img/avatars/4.jpg',
      name: 'Bonner Mcmillan',
      phone: '+13 (932) 426-2309',
      designation: 'Software developer',
      email: 'bonner.mcmillan@magneato.io',
      employeeStartDate: new Date('2023-05-10'),
      publicHolidayGroup: 'bangladesh',
      onBoardingMentor: 'Sophia Martinez',
      directManager: 'James Johnson',
      location: 'dhaka',
      team: 'java',
      employeeStatus: 'full-time'
    },
    {
      id: 5,
      imageSrc: 'assets/img/avatars/5.jpg',
      name: 'Velasquez Spence',
      phone: '+31 (850) 492-2858',
      designation: 'Software developer',
      email: 'velasquez.spence@joviold.co.uk',
      employeeStartDate: new Date('2019-07-22'),
      publicHolidayGroup: 'india',
      onBoardingMentor: 'Liam Harris',
      directManager: 'Olivia Davis',
      location: 'amsterdam',
      team: 'marketing',
      employeeStatus: 'full-time'
    },
    {
      id: 6,
      imageSrc: 'assets/img/avatars/6.jpg',
      name: 'Orr Fernandez',
      phone: '+6 (843) 490-2487',
      designation: 'Accountant',
      email: 'orr.fernandez@accuprint.tv',
      employeeStartDate: new Date('2018-09-14'),
      publicHolidayGroup: 'general',
      onBoardingMentor: 'Lucas Miller',
      directManager: 'Charlotte Taylor',
      location: 'london',
      team: 'sqa',
      employeeStatus: 'full-time'
    },
    {
      id: 7,
      imageSrc: 'assets/img/avatars/7.jpg',
      name: 'Marcella Russo',
      phone: '+48 (836) 506-2890',
      designation: 'Accountant',
      email: 'marcella.russo@paprikut.name',
      employeeStartDate: new Date('2023-01-20'),
      publicHolidayGroup: 'us',
      onBoardingMentor: 'Isabella Brown',
      directManager: 'Liam Wilson',
      location: 'new-york',
      team: 'angular',
      employeeStatus: 'full-time'
    },
    {
      id: 8,
      imageSrc: 'assets/img/avatars/8.jpg',
      name: 'Mccormick Ferguson',
      phone: '+8 (957) 553-2497',
      designation: 'Accountant',
      email: 'mccormick.ferguson@waab.info',
      employeeStartDate: new Date('2020-04-17'),
      publicHolidayGroup: 'india',
      onBoardingMentor: 'Ethan Moore',
      directManager: 'Mia Martinez',
      location: 'dhaka',
      team: 'devops',
      employeeStatus: 'full-time'
    },
    {
      id: 9,
      imageSrc: 'assets/img/avatars/9.jpg',
      name: 'Myrtle Walters',
      phone: '+29 (846) 562-3339',
      designation: 'Designer',
      email: 'myrtle.walters@hinway.me',
      employeeStartDate: new Date('2019-12-11'),
      publicHolidayGroup: 'bangladesh',
      onBoardingMentor: 'Sophia Thomas',
      directManager: 'William Lee',
      location: 'london',
      team: 'marketing',
      employeeStatus: 'full-time'
    },
    {
      id: 10,
      imageSrc: 'assets/img/avatars/10.jpg',
      name: 'Rachael Griffin',
      phone: '+26 (827) 437-3065',
      designation: 'Designer',
      email: 'rachael.griffin@callflex.net',
      employeeStartDate: new Date('2021-06-23'),
      publicHolidayGroup: 'general',
      onBoardingMentor: 'Mason Clark',
      directManager: 'Ava Walker',
      location: 'new-york',
      team: 'java',
      employeeStatus: 'full-time'
    },
    {
      id: 11,
      imageSrc: 'assets/img/avatars/11.jpg',
      name: 'Carney Emerson',
      phone: '+24 (821) 560-2716',
      designation: 'Designer',
      email: 'carney.emerson@motovate.ca',
      employeeStartDate: new Date('2021-06-23'),
      publicHolidayGroup: 'general',
      onBoardingMentor: 'Mason Clark',
      directManager: 'Ava Walker',
      location: 'new-york',
      team: 'java',
      employeeStatus: 'full-time'
    },
    {
      id: 12,
      imageSrc: 'assets/img/avatars/12.jpg',
      name: 'Katrina Cooke',
      phone: '+10 (904) 524-2485',
      designation: 'Designer',
      email: 'katrina.cooke@quarex.biz',
      employeeStartDate: new Date('2023-01-20'),
      publicHolidayGroup: 'us',
      onBoardingMentor: 'Isabella Brown',
      directManager: 'Liam Wilson',
      location: 'new-york',
      team: 'angular',
      employeeStatus: 'full-time'
    },
    {
      id: 13,
      imageSrc: 'assets/img/avatars/13.jpg',
      name: 'Valdez Branch',
      phone: '+12 (941) 536-2874',
      designation: 'Designer',
      email: 'valdez.branch@uniworld.com',
      employeeStartDate: new Date('2023-01-20'),
      publicHolidayGroup: 'us',
      onBoardingMentor: 'Isabella Brown',
      directManager: 'Liam Wilson',
      location: 'new-york',
      team: 'angular',
      employeeStatus: 'full-time'
    },
    {
      id: 14,
      imageSrc: 'assets/img/avatars/14.jpg',
      name: 'Dejesus Rogers',
      phone: '+40 (806) 435-2871',
      designation: 'Designer',
      email: 'dejesus.rogers@oronoko.biz',
      employeeStartDate: new Date('2023-01-20'),
      publicHolidayGroup: 'us',
      onBoardingMentor: 'Isabella Brown',
      directManager: 'Liam Wilson',
      location: 'new-york',
      team: 'angular',
      employeeStatus: 'full-time'
    },
    {
      id: 15,
      imageSrc: 'assets/img/avatars/15.jpg',
      name: 'Horton Levy',
      phone: '+19 (932) 552-3976',
      designation: 'Designer',
      email: 'horton.levy@zensus.org',
      employeeStartDate: new Date('2023-01-20'),
      publicHolidayGroup: 'us',
      onBoardingMentor: 'Isabella Brown',
      directManager: 'Liam Wilson',
      location: 'new-york',
      team: 'angular',
      employeeStatus: 'full-time'
    },
    {
      id: 16,
      imageSrc: 'assets/img/avatars/16.jpg',
      name: 'Ivy Mays',
      phone: '+15 (919) 430-3795',
      designation: 'Designer',
      email: 'ivy.mays@letpro.io',
      employeeStartDate: new Date('2023-01-20'),
      publicHolidayGroup: 'us',
      onBoardingMentor: 'Isabella Brown',
      directManager: 'Liam Wilson',
      location: 'new-york',
      team: 'angular',
      employeeStatus: 'full-time'
    },
    {
      id: 17,
      imageSrc: 'assets/img/avatars/17.jpg',
      name: 'Butler Larsen',
      phone: '+18 (862) 489-2364',
      designation: 'Designer',
      email: 'butler.larsen@micronaut.co.uk',
      employeeStartDate: new Date('2019-12-11'),
      publicHolidayGroup: 'bangladesh',
      onBoardingMentor: 'Sophia Thomas',
      directManager: 'William Lee',
      location: 'london',
      team: 'marketing',
      employeeStatus: 'full-time'
    },
    {
      id: 18,
      imageSrc: 'assets/img/avatars/18.jpg',
      name: 'Jimmie Clements',
      phone: '+34 (946) 451-3718',
      designation: 'Designer',
      email: 'jimmie.clements@sarasonic.tv',
      employeeStartDate: new Date('2019-12-11'),
      publicHolidayGroup: 'bangladesh',
      onBoardingMentor: 'Sophia Thomas',
      directManager: 'William Lee',
      location: 'london',
      team: 'marketing',
      employeeStatus: 'full-time'
    },
    {
      id: 19,
      imageSrc: 'assets/img/avatars/19.jpg',
      name: 'Kasey Rosa',
      phone: '+44 (910) 404-3456',
      designation: 'Ofice stuff',
      email: 'kasey.rosa@cytrak.name',
      employeeStartDate: new Date('2019-12-11'),
      publicHolidayGroup: 'bangladesh',
      onBoardingMentor: 'Sophia Thomas',
      directManager: 'William Lee',
      location: 'london',
      team: 'marketing',
      employeeStatus: 'full-time'
    },
    {
      id: 20,
      imageSrc: 'assets/img/avatars/20.jpg',
      name: 'Emily Schneider',
      phone: '+40 (870) 564-3250',
      designation: 'Ofice stuff',
      email: 'emily.schneider@noralex.info',
      employeeStartDate: new Date('2019-12-11'),
      publicHolidayGroup: 'bangladesh',
      onBoardingMentor: 'Sophia Thomas',
      directManager: 'William Lee',
      location: 'london',
      team: 'marketing',
      employeeStatus: 'full-time'
    },
    {
      id: 21,
      imageSrc: 'assets/img/avatars/20.jpg',
      name: 'Lara Witt',
      phone: '+29 (971) 550-3793',
      designation: 'Ofice stuff',
      email: 'lara.witt@moltonic.me',
      employeeStartDate: new Date('2019-12-11'),
      publicHolidayGroup: 'bangladesh',
      onBoardingMentor: 'Sophia Thomas',
      directManager: 'William Lee',
      location: 'london',
      team: 'marketing',
      employeeStatus: 'full-time'
    },
    {
      id: 22,
      imageSrc: 'assets/img/avatars/19.jpg',
      name: 'Hebert Bailey',
      phone: '+4 (884) 527-3408',
      designation: 'Tester',
      email: 'hebert.bailey@homelux.net',
      employeeStartDate: new Date('2020-04-17'),
      publicHolidayGroup: 'india',
      onBoardingMentor: 'Ethan Moore',
      directManager: 'Mia Martinez',
      location: 'dhaka',
      team: 'devops',
      employeeStatus: 'full-time'
    },
    {
      id: 23,
      imageSrc: 'assets/img/avatars/18.jpg',
      name: 'Lynda Garza',
      phone: '+44 (872) 404-3519',
      designation: 'Tester',
      email: 'lynda.garza@quonk.ca',
      employeeStartDate: new Date('2020-04-17'),
      publicHolidayGroup: 'india',
      onBoardingMentor: 'Ethan Moore',
      directManager: 'Mia Martinez',
      location: 'dhaka',
      team: 'devops',
      employeeStatus: 'full-time'
    },
    {
      id: 24,
      imageSrc: 'assets/img/avatars/17.jpg',
      name: 'Stark Fitzgerald',
      phone: '+7 (999) 438-2471',
      designation: 'Tester',
      email: 'stark.fitzgerald@farmage.biz',
      employeeStartDate: new Date('2020-04-17'),
      publicHolidayGroup: 'bangladesh',
      onBoardingMentor: 'Ethan Moore',
      directManager: 'Mia Martinez',
      location: 'dhaka',
      team: 'devops',
      employeeStatus: 'full-time'
    },
    {
      id: 25,
      imageSrc: 'assets/img/avatars/16.jpg',
      name: 'Karla Atkins',
      phone: '+44 (869) 502-3263',
      designation: 'Tester',
      email: 'karla.atkins@kiggle.com',
      employeeStartDate: new Date('2020-04-17'),
      publicHolidayGroup: 'bangladesh',
      onBoardingMentor: 'Ethan Moore',
      directManager: 'Mia Martinez',
      location: 'dhaka',
      team: 'devops',
      employeeStatus: 'full-time'
    },
    {
      id: 26,
      imageSrc: 'assets/img/avatars/15.jpg',
      name: 'Wilkerson Beasley',
      phone: '+29 (889) 462-3929',
      designation: 'Tester',
      email: 'wilkerson.beasley@naxdis.biz',
      employeeStartDate: '2022-01-20',
      publicHolidayGroup: 'general',
      onBoardingMentor: 'Liam Johnson',
      directManager: 'Sophia Martinez',
      location: 'dhaka',
      team: 'testing',
      employeeStatus: 'full-time'
  },
  {
      id: 27,
      imageSrc: 'assets/img/avatars/14.jpg',
      name: 'Webb Stark',
      phone: '+38 (864) 482-2108',
      designation: 'Tester',
      email: 'webb.stark@equitax.org',
      employeeStartDate: '2023-03-15',
      publicHolidayGroup: 'uk',
      onBoardingMentor: 'Emma Wilson',
      directManager: 'Oliver Taylor',
      location: 'london',
      team: 'testing',
      employeeStatus: 'full-time'
  },
  {
      id: 28,
      imageSrc: 'assets/img/avatars/13.jpg',
      name: 'Courtney Barrett',
      phone: '+6 (828) 438-3288',
      designation: 'Tester',
      email: 'courtney.barrett@magnemo.io',
      employeeStartDate: '2021-05-10',
      publicHolidayGroup: 'india',
      onBoardingMentor: 'Ava Scott',
      directManager: 'Liam Smith',
      location: 'new-york',
      team: 'testing',
      employeeStatus: 'full-time'
  },
  {
      id: 29,
      imageSrc: 'assets/img/avatars/12.jpg',
      name: 'Joanne Anderson',
      phone: '+27 (994) 435-2952',
      designation: 'Tester',
      email: 'joanne.anderson@extragene.co.uk',
      employeeStartDate: '2020-11-25',
      publicHolidayGroup: 'us',
      onBoardingMentor: 'Noah Brown',
      directManager: 'Mia Davis',
      location: 'dhaka',
      team: 'testing',
      employeeStatus: 'full-time'
  },
  {
      id: 30,
      imageSrc: 'assets/img/avatars/11.jpg',
      name: 'Hampton Golden',
      phone: '+1 (967) 549-3561',
      designation: 'Tester',
      email: 'hampton.golden@accupharm.tv',
      employeeStartDate: '2022-08-30',
      publicHolidayGroup: 'bangladesh',
      onBoardingMentor: 'Isabella Walker',
      directManager: 'James Johnson',
      location: 'amsterdam',
      team: 'testing',
      employeeStatus: 'full-time'
  },
  {
      id: 31,
      imageSrc: 'assets/img/avatars/10.jpg',
      name: 'Becker Mejia',
      phone: '+16 (971) 587-3994',
      designation: 'Tester',
      email: 'becker.mejia@zillacom.name',
      employeeStartDate: '2023-06-10',
      publicHolidayGroup: 'general',
      onBoardingMentor: 'Charlotte Lee',
      directManager: 'Oliver Smith',
      location: 'london',
      team: 'testing',
      employeeStatus: 'full-time'
  },
  {
      id: 32,
      imageSrc: 'assets/img/avatars/9.jpg',
      name: 'Marks Benton',
      phone: '+25 (961) 567-2085',
      designation: 'CEO',
      email: 'marks.benton@emoltra.info',
      employeeStartDate: '2018-01-12',
      publicHolidayGroup: 'uk',
      onBoardingMentor: 'Sophia Martinez',
      directManager: 'Michael Brown',
      location: 'new-york',
      team: 'management',
      employeeStatus: 'full-time'
  },
  {
      id: 33,
      imageSrc: 'assets/img/avatars/8.jpg',
      name: 'Mai Wade',
      phone: '+23 (970) 419-3433',
      designation: 'Team lead',
      email: 'mai.wade@senmao.me',
      employeeStartDate: '2020-03-05',
      publicHolidayGroup: 'india',
      onBoardingMentor: 'Emily Johnson',
      directManager: 'Ethan White',
      location: 'dhaka',
      team: 'management',
      employeeStatus: 'full-time'
  },
  {
      id: 34,
      imageSrc: 'assets/img/avatars/7.jpg',
      name: 'Maldonado Moran',
      phone: '+6 (912) 523-3028',
      designation: 'Team lead',
      email: 'maldonado.moran@autograte.net',
      employeeStartDate: '2021-07-20',
      publicHolidayGroup: 'us',
      onBoardingMentor: 'Oliver Taylor',
      directManager: 'Liam Harris',
      location: 'amsterdam',
      team: 'management',
      employeeStatus: 'full-time'
  },
  {
      id: 35,
      imageSrc: 'assets/img/avatars/6.jpg',
      name: 'Jaclyn Maxwell',
      phone: '+39 (988) 424-2719',
      designation: 'Team lead',
      email: 'jaclyn.maxwell@ecratic.ca',
      employeeStartDate: '2022-02-15',
      publicHolidayGroup: 'bangladesh',
      onBoardingMentor: 'Ava Clark',
      directManager: 'Emma Johnson',
      location: 'london',
      team: 'management',
      employeeStatus: 'full-time'
  },
  {
      id: 36,
      imageSrc: 'assets/img/avatars/5.jpg',
      name: 'Carmela Barron',
      phone: '+44 (932) 469-3459',
      designation: 'Operator',
      email: 'carmela.barron@xinware.biz',
      employeeStartDate: '2021-09-10',
      publicHolidayGroup: 'general',
      onBoardingMentor: 'Sophia Lee',
      directManager: 'Liam Thompson',
      location: 'new-york',
      team: 'operations',
      employeeStatus: 'full-time'
  },
  {
      id: 37,
      imageSrc: 'assets/img/avatars/4.jpg',
      name: 'Araceli Velasquez',
      phone: '+43 (965) 579-3919',
      designation: 'Operator',
      email: 'araceli.velasquez@capscreen.com',
      employeeStartDate: '2022-11-05',
      publicHolidayGroup: 'uk',
      onBoardingMentor: 'Emma Brown',
      directManager: 'James Smith',
      location: 'dhaka',
      team: 'operations',
      employeeStatus: 'full-time'
  },
  {
      id: 38,
      imageSrc: 'assets/img/avatars/3.jpg',
      name: 'Gonzales Randolph',
      phone: '+23 (951) 574-3150',
      designation: 'Operator',
      email: 'gonzales.randolph@ronbert.biz',
      employeeStartDate: '2023-04-18',
      publicHolidayGroup: 'india',
      onBoardingMentor: 'Noah Clark',
      directManager: 'Mason Johnson',
      location: 'amsterdam',
      team: 'operations',
      employeeStatus: 'full-time'
  },
  {
      id: 39,
      imageSrc: 'assets/img/avatars/2.jpg',
      name: 'Ramirez Burt',
      phone: '+24 (963) 484-3465',
      designation: 'Operator',
      email: 'ramirez.burt@quizmo.org',
      employeeStartDate: '2020-05-14',
      publicHolidayGroup: 'us',
      onBoardingMentor: 'Isabella Lee',
      directManager: 'Olivia Wilson',
      location: 'new-york',
      team: 'operations',
      employeeStatus: 'full-time'
  },
  {
      id: 40,
      imageSrc: 'assets/img/avatars/1.jpg',
      name: 'Jessica Frenz',
      phone: '+49 (332) 45-4234',
      designation: 'Operator',
      email: 'jessica.frenz@bongo.com',
      employeeStartDate: '2021-10-22',
      publicHolidayGroup: 'bangladesh',
      onBoardingMentor: 'Emma White',
      directManager: 'Liam Davis',
      location: 'dhaka',
      team: 'operations',
      employeeStatus: 'full-time'
  }  
  ];